workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fix Isar compatibility with modern Flutter
        script: |
          echo "Configuring for modern Flutter with Isar compatibility..."
          # Fix gradle.properties first
          if [ -f "android/gradle.properties" ]; then
            echo "Original gradle.properties:"
            cat android/gradle.properties
            
            # Remove the deprecated line if it exists
            grep -v "android.enableR8" android/gradle.properties > android/gradle.properties.tmp 2>/dev/null || cp android/gradle.properties android/gradle.properties.tmp
            mv android/gradle.properties.tmp android/gradle.properties
            
            echo "Fixed gradle.properties:"
            cat android/gradle.properties
          fi
          
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Generate code if needed (Isar, build_runner)
        script: |
          if grep -q "build_runner" pubspec.yaml; then
            echo "Running build_runner for code generation..."
            flutter packages pub run build_runner build --delete-conflicting-outputs
          else
            echo "No build_runner dependency found, skipping code generation"
          fi
          
      - name: Build debug APK
        script: |
          flutter build apk --debug --android-skip-build-dependency-validation
          
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true