workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Build APK (ignore Flutter's file detection error)
        script: |
          echo "=== Building APK ==="
          # Run flutter build but ignore the exit code since Gradle succeeds
          flutter build apk --release --verbose || true
          
      - name: Find and copy APK from Android build directory
        script: |
          echo "=== Looking for APK in Android build outputs ==="
          
          # Check the actual Android build output directory
          APK_DIR="android/app/build/outputs/apk/release"
          if [ -d "$APK_DIR" ]; then
            echo "Found APK directory: $APK_DIR"
            ls -la "$APK_DIR"
            
            # Find the APK file
            APK_FILE=$(find "$APK_DIR" -name "*.apk" | head -1)
            if [ -n "$APK_FILE" ]; then
              echo "Found APK: $APK_FILE"
              mkdir -p artifacts
              cp "$APK_FILE" artifacts/app-release.apk
              ls -la artifacts/
              echo "✅ APK successfully copied!"
            else
              echo "❌ No APK file found in $APK_DIR"
              exit 1
            fi
          else
            echo "❌ APK directory $APK_DIR not found"
            echo "Searching all possible locations..."
            find android/app/build -name "*.apk" -type f 2>/dev/null || echo "No APK files found anywhere"
            exit 1
          fi
          
    artifacts:
      - artifacts/*.apk
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/**/*.apk