workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Find and copy APK
        script: |
          echo "=== Searching for APK files ==="
          APK_PATH=$(find build -name "*.apk" -type f | head -1)
          if [ -n "$APK_PATH" ]; then
            echo "Found APK at: $APK_PATH"
            mkdir -p artifacts
            cp "$APK_PATH" artifacts/app-release.apk
            echo "APK copied to artifacts/app-release.apk"
          else
            echo "No APK file found!"
            echo "Build directory contents:"
            find build -type f -name "*.apk" 2>/dev/null || echo "No APK files found anywhere"
            ls -la build/ 2>/dev/null || echo "Build directory doesn't exist"
          fi
    artifacts:
      - artifacts/*.apk
      - build/**/*.apk
      - build/**/*.aab