workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: flutter clean
        
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Generate Isar files
        script: |
          echo "=== Generating Isar schema files ==="
          flutter packages pub run build_runner build --delete-conflicting-outputs
        
      - name: Check Android configuration
        script: |
          echo "=== Checking Android configuration ==="
          echo "Java version:"
          java -version
          echo "Gradle version:"
          cd android && ./gradlew --version
          echo "Android build files:"
          ls -la android/app/build.gradle*
          
      - name: Build APK with detailed logging
        script: |
          echo "=== Building APK with detailed logging ==="
          cd android
          ./gradlew assembleRelease --stacktrace --info --warning-mode all
          
      - name: Find and copy APK
        script: |
          echo "=== Looking for APK ==="
          find . -name "*.apk" -type f
          
          APK_DIR="android/app/build/outputs/apk/release"
          if [ -d "$APK_DIR" ]; then
            APK_FILE=$(find "$APK_DIR" -name "*.apk" | head -1)
            if [ -n "$APK_FILE" ]; then
              mkdir -p artifacts
              cp "$APK_FILE" artifacts/app-release.apk
              echo "✅ APK copied successfully!"
            fi
          fi
          
    artifacts:
      - artifacts/*.apk